export enum DispatchType {
  addFavorites = "ADD_FAVORITES",
  addWarnings = "ADD_WARNINGS",
  delFavorites = "DEL_FAVORITES",
  delWarnings = "DEL_WARNINGS",
  getFavorites = "GET_FAVORITES",
  getWeek = "GET_WEEK",
  getWarnings = "GET_WARNINGS",
  requestWeek = "REQUEST_WEEK",
  setAcceptedNotification = "SET_ACCEPTED_NOTIFICATION",
  setFavorites = "SET_FAVORITES",
  setWeek = "SET_WEEK",
  setNewWarning = "SET_NEW_WARNING",
  setWarnings = "SET_WARNINGS",
  setIsRequesting = "SET_IS_REQUESTING",
  setIsAppReady = "SET_IS_APP_READY",
  setTextFailed = "SET_TEXT_FAILED",
  setSuccess = "SET_SUCCESS",
  updateWeek = "UPDATE_WEEK",
  setDay = "SET_DAY",
  setThereIsWarning = "SET_THERE_IS_WARN",
  setConfigurations = "SET_CONFIGURATIONS",
  getConfigurations = "GET_CONFIGURATIONS",
  updateConfigurations = "UPDATE_CONFIGURATIONS"
}
